name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Pack with dotnet
      run: dotnet pack --configuration Release
#     - name: Publish in nuget
#       run: dotnet nuget push "bin/Release/Xamarin.Forms.XamlPack.1.0.0.nupkg" --source "github"
